"""Init

Revision ID: 97bd8c40e2d5
Revises: 
Create Date: 2019-10-07 23:39:56.524903

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '97bd8c40e2d5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('route_edges',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('edge_key', sa.String(length=100), nullable=False),
    sa.Column('points', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('edge_key')
    )
    op.create_index(op.f('ix_route_edges_created_at'), 'route_edges', ['created_at'], unique=False)
    op.create_index(op.f('ix_route_edges_edge_key'), 'route_edges', ['edge_key'], unique=True)
    op.create_index(op.f('ix_route_edges_updated_at'), 'route_edges', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_route_edges_updated_at'), table_name='route_edges')
    op.drop_index(op.f('ix_route_edges_edge_key'), table_name='route_edges')
    op.drop_index(op.f('ix_route_edges_created_at'), table_name='route_edges')
    op.drop_table('route_edges')
    # ### end Alembic commands ###
